<?php
namespace App ;
use App\Serveur;

class Imprimante extends EquipementReseau {

    private string $type ;
    private bool $estCouleur ;

    public function __construct(string $typeParam, bool $estCouleurParam, string $ipParam, string $hostnameParam ){
        $this->type = $typeParam ;
        $this->estCouleur = $estCouleurParam ;

        parent::__construct($hostnameParam, $ipParam);

    }

    public function afficherStatut(): string
    {

        $afficheCouleur = "NON";
        if ($this->estCouleur)
            $afficheCouleur = "OUI";
        return parent::afficherStatut()."| Type : ".$this->type." | Couleur : ".$afficheCouleur  ; // TODO: Change the autogenerated stub
    }

}